# -*- mode: ruby -*-
# vi: set ft=ruby :

# Ipython port to forward (also set in IPython notebook config)
ipythonPort = 8001

Vagrant.configure(2) do |config|
  config.ssh.insert_key = true
  config.vm.define "sparkvm" do |master|
    master.vm.box = "sparkmooc/base"
    master.vm.box_url = "/Users/hqlgree2/Downloads/software/sparkvm.box"
    master.vm.box_download_insecure = true
    master.vm.boot_timeout = 900
    # IPython port (set in notebook config)
    master.vm.network :forwarded_port, host: ipythonPort, guest: ipythonPort, auto_correct: true
    # Spark UI (Driver)
    master.vm.network :forwarded_port, host: 4040, guest: 4040, auto_correct: true
    master.vm.hostname = "sparkvm"
    master.vm.usable_port_range = 4040..4090

    master.vm.provider :virtualbox do |v|
      v.name = master.vm.hostname.to_s
    end
  end
end
